feat/english getting-Started
FlowSquad/miranum-docs pull request #7
Opened 2023-02-01 09:05 UTC by J-Mertl

2023-02-02 14:57 UTC, DaAnda97 requested changes
Die Texte lesen sich ganz gut. Nur ich würd die Website gern sehn. Kannst dus bitte irgendwo deployen? Vll via Github Pages oder Netlify?

2023-02-02 14:58 UTC, DaAnda97 commented
jetzt seh ich grad, dass die Website schon auf netlify deplyed wird. Kannst du den Link bitte in die Readme packen?

2023-02-02 15:34 UTC, J-Mertl commented
meinst du so?
Oder lokal? Weil lokal gehts über npm start

2023-02-03 11:31 UTC, DaAnda97 commented
Ich hätte die Readme generell überarbeitet. Die aktuelle Version ist ja die auto-generierte von Dokusaurus.
Ich hätts irgendwie so aufgebaut:

## miranum-website
This repository contains the code our [website](url) is build with.

### development
You'd like to contribute? You're welcome!

The website is developed using docusaurus (Kurze Beschreibung, was das ist + Link zur Doku)

For local development please run `yarn install` and `yarn start` in the root directory. The application will be available at http:://localhost:<PORT>

### deployment
Our public website is deployed on netlify. Create a pull request and after our review you'll see your changes online.

2023-02-03 11:41 UTC, merged